|                                                                     Specification                                                                    | Test case ID |                                                               Purpose                                                              |
|:----------------------------------------------------------------------------------------------------------------------------------------------------:|:------------:|:----------------------------------------------------------------------------------------------------------------------------------:|
|                                                   If the user hasn't logged in, show the login page                                                  |     R1.1     |                                  Tests that the login page will show if the user is not logged in                                  |
|                                           the login page has a message that by default says 'please login'                                           |     R1.2     |                                  Check if the login page has the message that says "please log in"                                 |
|                                             If the user has logged in, redirect to the user profile page                                             |     R1.3     | Checks that if the user is able to log in using the correct information then the application will bring them to their profile page |
|                                  The login page provides a login form which requests two fields: email and passwords                                 |     R1.4     |                 Checks to make sure that the login page contains both of the email and password forms to be filled                 |
|                            Test case R1.5 - The login form can be submitted as a POST request to the current URL (/login)                            |     R1.5     |                                    Check that when the user submits the login it will point to /                                   |
|                                                        Email and password both cannot be empty                                                       |     R1.6     |                                    Checks that the email and password fields are both not empty                                    |
|                                                   Email has to follow addr-spec defined in RFC 5322                                                  |     R1.7P    |                                      Checks that the users email follows RFC 5322 and submits                                      |
|                                                   Email has to follow addr-spec defined in RFC 5322                                                  |     R1.7N    |                            Checks that the page throws an error when the email does not follow RFC 5322                            |
| Password has to meet the required complexity: minimum length 6, at least one upper case, at least one lower case, and at least one special character |     R1.8P    |                 Checks that when the user enters a correct password, the website will bring them to their homepage                 |
| Password has to meet the required complexity: minimum length 6, at least one upper case, at least one lower case, and at least one special character |     R1.8N    |          CHecks that when the user enters a password that has incorrect form, it will throw an error for any of the cases          |
|                      For any formatting errors, render the login page and show the message 'email/password format is incorrect.'                     |     R1.9P    |                          Validates that when there is no formatting errors the program continues as normal                         |
|                      For any formatting errors, render the login page and show the message 'email/password format is incorrect.'                     |     R1.9N    |                           When there is a formatting error with the email the website will throw an error                          |
|                                                     If email/password are correct, redirect to /                                                     |     R1.10    |                                Verifies the user info entered is correct the page will redirect to /                               |
|                                  Otherwise, redict to /login and show message 'email/password combination incorrect'                                 |     R1.11    |                   Checks that if a wrong password or email combination is entered it will redirect to login page                   |
